[project]
name = "hackatum25-sixt-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.121.3",
    "groq>=0.36.0",
    "python-dotenv>=1.2.1",
    "uvicorn[standard]>=0.38.0",
]
